### ISSUE TITLE
Possible issue with Linux build script being too strict

### ISSUE THREAD

**Issue by n8willis** [tonton-pixel/unicopedia-plus#10]
You can certainly blame this on me poking at things I shouldn't but: I was making a brief foray into seeing if I could generate a snap package for this application, and it seems like the mere presence of an extra file in the top-level directory causes that `build-linux` to panic and give up.

Specifically, I had written a skeleton snapcraft.yaml file (this is following the Node instructions at https://snapcraft.io/docs/node-apps which suggest that's all that's required) and not even saved it. Without even getting into testing the snapcraft.yaml file, however, when I ran `npm run build-linux`, it failed with this:

```
> unicopedia-plus@8.10.0 build-linux /home/n8willis/code/unicopedia-plus
> electron-packager . --asar --out=build --platform=linux --ignore=/~.* --ignore=^/screenshots --icon=icons/icon.png --overwrite

Packaging app for platform linux x64 using electron v11.1.1
ENOENT: no such file or directory, stat '.#snapcraft.yaml'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! unicopedia-plus@8.10.0 build-linux: `electron-packager . --asar --out=build --platform=linux --ignore=/~.* --ignore=^/screenshots --icon=icons/icon.png --overwrite`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the unicopedia-plus@8.10.0 build-linux script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/n8willis/.npm/_logs/2021-01-19T12_43_51_108Z-debug.log
```

The file that it tripped on was `.#snapcraft.yaml` which is, of course, the Emacs autosave filename since I hadn't even saved my attempted yaml file. When I deleted it, the build ran perfectly fine.

Personally, I'd like to see this app packaged via snap for the sake of simplicity, but even if you've got no interest in that, it does seem like the build script is overreacting by failing because of the presence of that .dotfile.

**Comment by tonton-pixel** [comment]
Sorry, I  am indeed interested in keeping the building process of my Electron apps as simple as possible, with "plain vanilla" commands, making use of simple tools such as `electron-packager`.

You may want to try modifying the `build-linux` command step by step in `package.json` until it works as it should (the `--overwrite` option might be the cause of the issue and could be safely removed, I guess); if not, you can probably report the problem directly to [Electron Packager Issues](https://github.com/electron/electron-packager/issues) or check if somebody else has already reported or/and solved it.

BTW, according to [Electron apps | Snapcraft documentation](https://snapcraft.io/docs/electron-apps), `electron-builder` appears to be recommended over `electron-packager` for this task...
