### ISSUE TITLE
Universal binary for macOS

### ISSUE THREAD

**Issue by dahlia** [tonton-pixel/unicopedia-plus#12]
The official build for macOS is currently a binary for x86-64.  In order to use it on Apple silicon Macs, it should be a universal binary, or at least both types of binaries should be distributed together.

Although I'm totally ignorant of Electron, recent versions of electron-builder seem to allow to create universal binaries for Intel and Apple silicon Macs.

**Comment by dahlia** [comment]
I tried to open *Unicode Plus.app* in the *unicopedia-plus-mac-arm64-11.2.1.zip*, but it failed with the following error:

<img width="372" alt="image" src="https://user-images.githubusercontent.com/12431/159123068-b6418dad-9d3c-442f-97bd-7401166e2f51.png">

I tried again with the *unicopedia-plus-mac-arm64-11.2.1.dmg*, and it showed me a different one:

<img width="372" alt="Screen Shot 2022-03-19 at 10 29 08 PM" src="https://user-images.githubusercontent.com/12431/159123110-a91cf523-1e61-43c8-97f1-38eeda610ff5.png">

**Comment by dahlia** [comment]
I cloned the repository and try to built one by myself: `git reset --hard v11.2.1 && npm i && npm run build-darwin`.  The result build seems to work well on my M1 Max MacBook Pro: [Unicopedia Plus-darwin-arm64-v11.2.1.tar.bz2](https://1drv.ms/u/s!AhZrJxnldyvWjnGzp-yRLI7gVb-Q?e=XI3b3I).

**Comment by tonton-pixel** [comment]
Thanks for your test results and new tests.
I'm afraid I'll have to wait until I can afford to upgrade my MacBook to a more recent model.
In the meanwhile, I'll remove the tentative arm64 binaries. I suppose the x86-64 binaries work under Rosetta2 anyway, albeit more slowly...

**Comment by tonton-pixel** [comment]
@dahlia

I did a few more tests to try to understand what was not working correctly, but to no avail...

However, I eventually tried to explicitely set both `platform` and `architecture` in the CLI options of `package-builder` and, after several attempts where the size of binaries would even go up to 800 MB! (possibly a cache problem), I found out that the *universal* version was finally a mere 218 MB, which is not *too* much compared to the original 150 MB.

According to the page [https://github.com/electron/universal](https://github.com/electron/universal), I was expecting it to be around 300 MB:

> The app is twice as big now, why?
> 
> Well, a Universal app isn't anything magical. It is literally the x64 app and the arm64 app glued together into a single application. It's twice as big because it contains two apps in one. 

I uploaded the `.dmg` file to the [latest releases](https://github.com/tonton-pixel/unicopedia-plus/releases) page. Could you give it a try and let me know about the result?

[https://github.com/tonton-pixel/unicopedia-plus/releases/download/v11.2.1/unicopedia-plus-mac-universal-11.2.1.dmg](https://github.com/tonton-pixel/unicopedia-plus/releases/download/v11.2.1/unicopedia-plus-mac-universal-11.2.1.dmg)

**Comment by dahlia** [comment]
> I uploaded the `.dmg` file to the [latest releases](https://github.com/tonton-pixel/unicopedia-plus/releases) page. Could you give it a try and let me know about the result?
> 
> https://github.com/tonton-pixel/unicopedia-plus/releases/download/v11.2.1/unicopedia-plus-mac-universal-11.2.1.dmg

This build works like a charm!  Thank you very much!

**Comment by dahlia** [comment]
Although it's off topic, [I tried to submit Unicopedia Plus to Homebrew Cask.](https://github.com/Homebrew/homebrew-cask/pull/120734)  If it's accepted Unicopedia Plus will be installable using `brew install unicopedia-plus` command.
