### ISSUE TITLE
[description edit request] Update README.md to show how to run on Windows

### ISSUE THREAD

**Issue by BSBMteam** [tonton-pixel/unicopedia-plus#14]
Thank you for your amazing program!! I am a noob when it comes to installing packages, and would like you to possibly update the README.md to help people install and run your program on Windows! Feel free to include this guide so that people can successfully run your program on Windows!

https://www.electronjs.org/docs/latest/tutorial/quick-start

**1) Go to directory where the Unicopedia-plus folder is. In Command Prompt, enter this command:**

`cd C:\Users\{username}\{WHEREVER YOU PUT THE CODE}\unicopedia-plus`

For example: `cd C:\Users\BobBaker\Desktop\unicopedia-plus`

**2) Install Node & NPM**
(Check if Node & NPM are installed. Put these 2 commands in Command Prompt:)
```
node -v
npm -v
```
(If they are installed, it should return a version number.)

 If not installed, go to:
 https://nodejs.org/en/download/
 (Please install Node.js using pre-built installers for your platform. You may encounter incompatibility issues with different development tools otherwise.)

**3) After installing Node & NPM, install Electron with this Command Prompt command:**

`npm install --save-dev electron`

**4) IN SUMMARY: Go to that website, then put these Command Prompt commands into command prompt to install Node & NPM, and Electron:**
https://nodejs.org/en/download/
```
node -v
npm -v
npm install --save-dev electron
```

**5) IN SUMMARY: After installing all the above,  do these Command Prompt commands to start the program:**
```
cd C:\Users\{username}\{WHEREVER YOU PUT THE CODE}\unicopedia-plus
npm start
```

**Comment by tonton-pixel** [comment]
Thanks for your interest in my project.

https://www.electronjs.org/docs/latest/tutorial/quick-start is a link to a tutorial explaining how to create a *new* Electron application from scratch: generating a `package.json` file, installing the `electron` framework for the first time, etc.

The instructions found in this repository's README.md are not platform-specific and should be adequate enough to run the application successfully.

Hopefully, more useful and detailed information can be found on StackExchange:

https://superuser.com/questions/1444103/how-can-non-coders-use-programs-on-github
