### ISSUE TITLE
Work around system-ui font?

### ISSUE THREAD

**Issue by 747** [tonton-pixel/unicopedia-plus#6]
There is a small UX issue regarding `font-family: system-ui` on Windows, that [Latin letters typography may deteriorate according to user's locale](https://infinnie.github.io/blog/2017/systemui.html). Actually, at least all CJK locales seem to output Latin letters from their tweaked CJK UI fonts, that result in bad bold and italic rendering.

Below are screenshots on my desktop, using `system-ui`:
![image](https://user-images.githubusercontent.com/3427854/96115108-6d7a4880-0f21-11eb-854a-2d8dea48e374.png)

replaced by `Segoe UI`:
![image](https://user-images.githubusercontent.com/3427854/96115188-85ea6300-0f21-11eb-9979-43a0d4b1625c.png)

As this is a universal app, I'm not sure how exactly it ought to be solved. For Windows, adding a decent Latin font at the head of `font-family` list (as I showed) would do.

---

```
-- Application --

Name: Unicopedia Plus
Version: 8.3.0
Date: 2020-10-15T10:23:41.911Z

Locale: ja
Packaged: true

-- Framework --

System Version: 10.0.18363
Platform: win32
Architecture: x64
Default App: false
Mac App Store App: false
Windows Store App: false
Electron Version: 10.1.3
Node Version: 12.16.3
V8 Version: 8.5.210.26-electron.0
Chromium Version: 85.0.4183.121
ICU Version: 67.1
Unicode Version: 13.0

-- Operating System --

OS Type: Windows_NT
OS Platform: win32
OS Release: 10.0.18363
CPU Architecture: x64
CPU Endianness: LE
CPU Logical Cores: 16
CPU Model: AMD Ryzen 7 1700 Eight-Core Processor          
CPU Speed (MHz): 2994
```

**Comment by tonton-pixel** [comment]
Thanks for opening this issue, and for your useful information.

Dealing with fonts through CSS is definitely a weak point of desktop applications based on web technology. I kind of remember having seen similar problems on Linux too.

Your suggestion of adding a decent Latin font at the head of the font stack is most certainly the way to go. I will have to apply such changes to several parts of the CSS code, and possibly test them under different locales too. This will benefit to my other Electron-based applications as well...

**Comment by tonton-pixel** [comment]
The latest release [8.3.1](https://github.com/tonton-pixel/unicopedia-plus/releases/tag/v8.3.1) should fix the issue that you kindly and efficiently reported. Please let me know if that is not the case on Windows. My tests on macOS and Linux tend to show that the `system-ui`font is performing just fine even when the locale is switched to `ja`, and the fix does not seem to have any side effect on these platforms, hopefully.

**Comment by 747** [comment]
Hi, thank you for the quick update. I rebuilt it and they look good to me.

The thing is that, I noticed that not only `system-ui` but the stack of `sans-serif` is tainted in the `ja` locale.

8.3.1 default: the sample glyphs are apparently shown in Meiryo font, non-JIS Latins are corrupt:
![image](https://user-images.githubusercontent.com/3427854/96204204-b8867100-0f9e-11eb-9a09-a2000e4d25d3.png)

Ironically, disabling `font-family` makes it "better" 😂:
![image](https://user-images.githubusercontent.com/3427854/96204426-43676b80-0f9f-11eb-9f6e-7204643cb004.png)

which seems identical with Segoe UI rendering on my env:
![image](https://user-images.githubusercontent.com/3427854/96204608-b7097880-0f9f-11eb-859a-29e05c33a077.png)

Since there is no similar report AFAIK from Chinese locales, I hope this is specifically a `ja` locale vs Latin/Cyrillic/Greek matter on Windows, that could be fixed with Segoe UI too.

**Comment by tonton-pixel** [comment]
Nice catch, @747!

This is apparently a bug which affects all platforms. Although I did test this app under Japanese or Chinese locales on macOS and Linux, I obviously focused only on CJK characters and failed to test complex Latin, Cyrillic, etc. characters as well. Or maybe Chromium font handling has been modified in recent versions, I don't know...

I'm self-opening a new Issue #7 on this bug and consequently closing this one.

Thank you for catching this. This is an important step for improvement, I believe.

**Comment by 747** [comment]
Thank you for your timely updates. Now with the new build it looks as great as it should be.
It is strange enough as I didn't remember noticing such a bug when I downloaded your software to my old machine around a year ago. Maybe I was blind...
