### ISSUE TITLE
Complex Latin characters are not correctly displayed under CJK locales

### ISSUE THREAD

**Issue by tonton-pixel** [tonton-pixel/unicopedia-plus#7]
Thanks to @747 who spotted this bug, in connection with [Issue #6](https://github.com/tonton-pixel/unicopedia-plus/issues/6).

This bug apparently affects all platforms: macOS, Linux, Windows.

The latest release [8.4.0](https://github.com/tonton-pixel/unicopedia-plus/releases/tag/v8.4.0) should fix this issue, by replacing all `font-family: system-ui` CSS declarations with `font-family: inherit`. Alternatively, getting rid of all these declarations could have just been sufficient, but for some reason, this failed for textarea fields.

**Comment by tonton-pixel** [comment]
Hopefully, release [8.10.0](https://github.com/tonton-pixel/unicopedia-plus/releases/tag/v8.10.0) does a far better job at managing font stacks that the previous quick hack introduced in 8.4.0. And, more importantly, all future modifications can be conveniently made in only one single CSS file from now on, in [custom.css](https://github.com/tonton-pixel/unicopedia-plus/blob/master/renderer/custom.css):

    --monospace-family: Monaco, Menlo, "DejaVu Sans Mono", "Liberation Mono", "Noto Mono", "Ubuntu Mono", monospace;
    --system-ui-family: "Segoe UI", system-ui, sans-serif;
    --sans-serif-family: Arial, Geneva, Verdana, Tahoma, "DejaVu Sans", "Liberation Sans", "Noto Sans", Ubuntu, sans-serif;
    --sans-serif-emoji-family: Arial, Geneva, Verdana, Tahoma, "DejaVu Sans", "Liberation Sans", "Noto Sans", Ubuntu, sans-serif, "Apple Color Emoji", "Noto Color Emoji", "Segoe UI Emoji", emoji;
    --emoji-family: "Apple Color Emoji", "Noto Color Emoji", "Segoe UI Emoji", emoji;
    --unihan-family: sans-serif;

These improvements have been thoroughly tested in macOS and Linux, under several CJK locales. For Windows, I would certainly be glad to get some feedback from power users such as @747 in case I introduced some kind of regression...

**Comment by 747** [comment]
Thank you for the update. I tried out the latest release.
Using it so far, I think I've found a defect in a Unihan property, but no apparent one of the app 👍.
I noticed the glyph examples now displayed in Arial in my env, where I think Segoe UI would be better on Windows in terms of visibility of diacritics.

**Comment by tonton-pixel** [comment]
@747 Thanks for your feedback.

I just released [v8.10.1](https://github.com/tonton-pixel/unicopedia-plus/releases/tag/v8.10.1) which updates font stacks, taking into account your suggestion:

    --monospace-family: "Segoe UI Mono", Monaco, Menlo, "DejaVu Sans Mono", "Liberation Mono", "Noto Mono", "Ubuntu Mono", monospace;
    --system-ui-family: "Segoe UI", system-ui, sans-serif;
    --sans-serif-family: "Segoe UI", Arial, Geneva, Verdana, Tahoma, "DejaVu Sans", "Liberation Sans", "Noto Sans", Ubuntu, sans-serif;
    --sans-serif-emoji-family: "Segoe UI", Arial, Geneva, Verdana, Tahoma, "DejaVu Sans", "Liberation Sans", "Noto Sans", Ubuntu, sans-serif, "Segoe UI Emoji", "Apple Color Emoji", "Noto Color Emoji", emoji;
    --emoji-family: "Segoe UI Emoji", "Apple Color Emoji", "Noto Color Emoji", emoji;
    --unihan-family: sans-serif;

I'm afraid I got somehow misled by the presence of "UI" in "Segoe UI" that I have associated too tightly to the `system-ui` generic family name...); it seems that this font is pretty popular, and good for general purpose too...

BTW, just out of curiosity, what is the defect you found in a Unihan property, is it a specific or global issue? I already proposed several corrections of the data in the Unihan database, many of them about Japanese, and I think there is still a lot of room for improvement...

**Comment by 747** [comment]
Thank you for your quick support as always.

Yes, it is confusing... Usually "UI" is put on specially tweaked fonts for fitting Windows UI needs, but this one is just an ordinary humanist typeface (slightly adjusted for reading on screen) based on the original "Segoe" that isn't shipped with Windows.

> BTW, just out of curiosity, what is the defect you found in a Unihan property, is it a specific or global issue?

Not a big deal. What I exactly found is that 萬 has `kAccountingNumeric` value `10000`. 萬 as such is a plain Traditional character for "ten thousand", not an anti-forgery spelling, thus I think should have `kPrimaryNumeric`.

**Comment by tonton-pixel** [comment]
> Not a big deal. What I exactly found is that 萬 has kAccountingNumeric value 10000. 萬 as such is a plain Traditional character for "ten thousand", not an anti-forgery spelling, thus I think should have kPrimaryNumeric.

FWIW, the CLDR tool [Number Format Tester](https://st.unicode.org/cldr-apps/numbers.jsp) appears to acknowledge the fact that 萬 can be used in a *cardinal-financial* string under some CJK locales.

Since 萬 is the traditional variant of 万, It could have the `kPrimaryNumeric` property as well, but it seems that *only one* property can be chosen among *kAccountingNumeric*, *kOtherNumeric*, and *kPrimaryNumeric*:

```
kAccountingNumeric: 仟伍佰叁参參壱壹弌弍弎弐拾捌柒漆玖肆萬貮貳贰阡陆陌陸 [26]
kOtherNumeric: 㐅㒃㠪㭍亖什仨兩卄卅卌叄幺廾廿𠀁𠁤𠃢𠄡𠤪𠦃𠦌𠦜𠫪𠫽𠬙𢎐𢦘𣬛𦉭 [30]
kPrimaryNumeric: 一七万三九二五亿億兆八六十千四百零 [17]
```

**Comment by 747** [comment]
Sorry for the late reply.

Yes, but when you see the entries of `kAccountingNumeric`, 萬 is the odd one out being a non-substitute character. If I can believe CLDR, it is never used in Simplified Chinese anyway, while always in Traditional. And if it were that the property takes priority over `kPrimaryNumeric` when it has accounting usage (different from plain _cardinal_) in any locale, 零 should go `kAccountingNumeric` as well because of the tester page you linked. So, it seems to have inconsistency either way.

I think I'll incorporate it in a document I'm preparing that discusses some prickles in numeric properties of Unihan.
