### ISSUE TITLE
Word segmentation issues

### ISSUE THREAD

**Issue by tonton-pixel** [tonton-pixel/unicopedia-plus#9]
The new **Unicode Segmenter** utility of **Unicopedia Plus** is making use of the new `Intl.Segmenter` API which is now  supported by the most recent versions of Electron/Chromium.

However, there are a few **word segmentation** issues which can be highlighted using text samples provided by the **Unicode Segmenter** utility. 

Apparently, Chromium is implementing the `Intl.Segmenter` API by making calls to the ICU C++ library, which suggests that the issues are at the library level.

And indeed, these issues can be confirmed when testing the same text strings in the [ICU Demonstration - ICU Segments](https://icu4c-demos.unicode.org/icu-bin/icusegments) page, provided no behind-the-scenes normalization is applied in-between to the text in the clipboard, when pasting (Safari) or copying (Firefox), for instance.

The following test sequences made of two code points get unexpectedly split when performing *word* segmentation, although they are correctly kept together when doing *grapheme* segmentation:

**• Han character followed by a Variation Selector:**

```
漢︀ <U+6F22 CJK UNIFIED IDEOGRAPH-6F22, U+FE00 VARIATION SELECTOR-1>
```
This is the standardized variation sequence of: `漢 <U+FA47 CJK COMPATIBILITY IDEOGRAPH-FA47>` (documented in [StandardizedVariants.txt](https://www.unicode.org/Public/UNIDATA/StandardizedVariants.txt)).

```
劍󠄁 <U+528D CJK UNIFIED IDEOGRAPH-528D, U+E0101 VARIATION SELECTOR-18>
```
This provides a Japanese variation of `劍 <U+528D CJK UNIFIED IDEOGRAPH-528D>` specific to `Adobe-Japan1`, as described in [IVD_Sequences.txt](https://www.unicode.org/ivd/data/2020-11-06/IVD_Sequences.txt).

**• Decomposed form of a voiced or semi-voiced kana (Hiragana and Katakana):**

```
で <U+3066 HIRAGANA LETTER TE, U+3099 COMBINING KATAKANA-HIRAGANA VOICED SOUND MARK>
```
This is the decomposed form of `で <U+3067 HIRAGANA LETTER DE>`

```
ぽ <U+307B HIRAGANA LETTER HO, U+309A COMBINING KATAKANA-HIRAGANA SEMI-VOICED SOUND MARK>
```
This is the decomposed form of `ぽ <U+307D HIRAGANA LETTER PO>`

```
ド <U+30C8 KATAKANA LETTER TO, U+3099 COMBINING KATAKANA-HIRAGANA VOICED SOUND MARK>
```
This is the decomposed form of `ド <U+30C9 KATAKANA LETTER DO>`

```
ピ <U+30D2 KATAKANA LETTER HI, U+309A COMBINING KATAKANA-HIRAGANA SEMI-VOICED SOUND MARK>
```
This is the decomposed form of `ピ <U+30D4 KATAKANA LETTER PI>`

**Comment by tonton-pixel** [comment]
This issue cannot be fixed at this application level. Hopefully, it will get corrected in a future ICU version (currently 67.1).

**Comment by tonton-pixel** [comment]
Testing the problematic examples on the alternate demo page [breaks - Unicode Segmentation](https://util.unicode.org/UnicodeJsps/breaks.jsp) (ICU version: 63.1) seems to give better results than on the [ICU Segments](https://icu4c-demos.unicode.org/icu-bin/icusegments) page (ICU Version: 65.1), i.e. the two-code-point sequences don't get unexpectedly split when performing word segmentation; however, results are slighly different on whole words, depending on whether the voiced and semi-voiced kana characters are composed or decomposed for instance.

**Comment by photopea** [comment]
Hi, is it possible to get in touch with you? 

I am creating a photo editor www.Photopea.com , which is should be able to execute all scripts (.jsx) and actions (.atn), that Adobe Photoshop can execute. It already works to a certain extent.

I think you understand these things much better than me. Can I get in touch with you to ask you some questions? You can get in touch with me at support@photopea.com
